config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :tweets
  root 'tweets#index'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader

    after_create :renzoku_hantei
        #投稿を作成したのちにrenzoku_hanteiを実行する。
        
        #↓がrenzoku_hanteiの中身
    private
    def renzoku_hantei
        puts "始まったよー！！"
        user = self.user
        today = user.remind_date
        toukoubi = created_at.to_date
        last_date = user.last_tweeted_date
        return if last_date == today
        #user.last_tweeted_dateがremind_date(今日の日付)と同じならカウントしない。同日に複数投稿してる場合にこの後の処理を全部なしにする。
        puts "同日投稿判定を潜り抜けたよ！"
            if last_date == today - 1
            #user.last_tweeted_date（前回投稿した日）がremind_date(今日の日付)より1低かったら(:例16日に投稿、前回の投稿は15日)なら、
            new_kaisuu = user.kaisuu.to_i + 1
            puts "回数が増えたよ！"
            else
            puts "1回目だよ！"
            new_kaisuu = 1
            end
        # kaisuuカラムにニュー回数を代入、last_tweeted_date(前回投稿日)にtoukoubi（今回投稿した日）を代入。
        user.update!(
        kaisuu: new_kaisuu,
        last_tweeted_date: today
        )
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  after_action :kakuninn, only:[:index]
    
    def index
      
      if params[:search] == nil
        @tweets= Tweet.all
      elsif params[:search] == ''
        @tweets= Tweet.all
      else
        @tweets = Tweet.where("name LIKE ? ",'%' + params[:search] + '%')
      end
      @tweets = @tweets.order(created_at: :desc)
    end
    

    def new
        @tweet = Tweet.new
      end
    
      def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      
      def show
        @tweet = Tweet.find(params[:id])
      end
     
      def edit
        @tweet = Tweet.find(params[:id])
      end
     
      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end
      
      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end
      
      private
      def tweet_params
        params.require(:tweet).permit(:name, :place, :memory, :overall, :image)
      end
      
    
      def kakuninn
        user = current_user
        time = Time.now
        jtime = Time.at(time, in: "+09:00")
        user.update!(
        remind_date: jtime
        )
      end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      
      
          if params[:search] == nil
            @tweets= Tweet.all
          elsif params[:search] == ''
            @tweets= Tweet.all
          else
            @tweets = Tweet.where("name LIKE ? ",'%' + params[:search] + '%')
          end
          @tweets = @tweets.order(created_at: :desc)
      
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end
     
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wasuremono</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    
    <%= f.label :place %>
    <%= f.text_field :place, :size => 140 %> 

    <%= f.label :memory %>
    <%= f.datetime_select :memory, :size => 140 %>
  
    <h5>総合評価</h5>
     <div class="post_form">
        <%= f.radio_button :overall, 5 ,id: 'star1'%>
        <label for="star1"><span class="text">重要</span>★</label>
    
        <%= f.radio_button :overall, 4 ,id: 'star2'%>
        <label for="star2"><span class="text">良い</span>★</label>
    
        <%= f.radio_button :overall, 3 ,id: 'star3'%>
        <label for="star3"><span class="text">普通</span>★</label>
    
        <%= f.radio_button :overall, 2 ,id: 'star4'%>
        <label for="star4"><span class="text">悪い</span>★</label>
    
        <%= f.radio_button :overall, 1 ,id: 'star5'%>
        <label for="star5"><span class="text">最悪</span>★</label>
     </div>
   
     <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/ichiran.html.erb
<h3>Tweet一覧</h3>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"tweets",action:"ichiran"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<%= link_to "新規投稿へ", new_tweet_path %>

<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<div class="tweets-container">


  <% @tweets.each do |t| %>
    <%= link_to t.user.name, user_path(t.user.id) %>
    <div class="tweet">
      <%= t.user.email %>
      <%= t.name %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.place %>
      <%= t.memory %>
     
      <div>
      <h2>総合評価：
      <span class="star-rating">
         <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
         <span class="star-rating-back">★★★★★</span>
      </span> 
      </h2>
      </div>
     
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= link_to "削除する", tweet_path(t.id), data: { turbo_method: :delete } %>
    </div>
  <% end %>
</div>

app/views/tweets/index.html.erb
<body class="index-page">
  <div class="index-container">
    <div class="left-text">Tidy up</div>
    <div class="right-text">Left behind</div>

    <%= image_tag 'road.jpg', class: "index-image" %>

    <div class="button-group">
      <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <%= link_to "マイページ", user_path(current_user.id) if user_signed_in? %>
      <%= link_to "新規投稿", new_tweet_path %>
    </div>
  </div>
</body>

app/views/tweets/new.html.erb
<%= form_for @tweet, html: { multipart: true, class: "tweet-form" } do |f| %>
  <div class="form-container">
    <div class="form-row">
      <label>写真</label>
      <%= f.file_field :image, class: "form-input image-input" %>
    </div>

    <div class="form-row">
      <label>名前</label>
      <%= f.text_field :name, class: "form-input" %>
    </div>

    <div class="form-row">
      <label>場所</label>
      <%= f.text_field :place, class: "form-input" %>
    </div>

    <div class="form-row">
      <label>日付</label>
      <%= f.datetime_select :memory, class: "form-input" %>
    </div>

    <div class="form-row stars">
      <label>星評価</label>
      <div class="rating">
        <div class="star-block">
          <span class="label-text">重要</span>
          <%= f.radio_button :overall, 5, id: 'star1' %>
          <label for="star1">★</label>
        </div>
        <div class="star-block">
          <span class="label-text">少し重要</span>
          <%= f.radio_button :overall, 4, id: 'star2' %>
          <label for="star2">★</label>
        </div>
        <div class="star-block">
          <span class="label-text">普通</span>
          <%= f.radio_button :overall, 3, id: 'star3' %>
          <label for="star3">★</label>
        </div>
        <div class="star-block">
          <span class="label-text">微妙</span>
          <%= f.radio_button :overall, 2, id: 'star4' %>
          <label for="star4">★</label>
        </div>
        <div class="star-block">
          <span class="label-text">必要なし</span>
          <%= f.radio_button :overall, 1, id: 'star5' %>
          <label for="star5">★</label>
        </div>
      </div>
    </div>

    <div class="form-row submit-btn">
      <%= f.submit "投稿", class: "submit-button" %>
    </div>
  </div>
<% end %>

<div class="back-link">
  <%= link_to "一覧に戻る", tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="tweet">
  <p><%= @tweet.name %></p>
  <%= image_tag @tweet.image_url, size: "250x200" if @tweet.image? %>
  <p><%= @tweet.place%></p>
  <p><%= @tweet.memory %></p>
  <div>
    <h2>総合評価：
    <span class="star-rating">
       <span class="star-rating-front" style="width: <%= getPercent(@tweet.overall) %>%;">★★★★★</span>
       <span class="star-rating-back">★★★★★</span>
    </span> 
    </h2>
    </div>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="mypage-wrapper">
  <div class="mypage">マイページ</div>

  <div class="show">名前 : <%= @user.name %></div>
  <div class="show">メールアドレス : <%= @user.email %></div>
  <div class="show">プロフィール : <%= @user.profile %></div>

  <% if current_user.kaisuu.present? %>
    <% if current_user.kaisuu == 1 %>
      <h1 class="warning">前日の投稿がされていません！</h1>
    <% else %>
      <div class="streak">現在の連続投稿回数 <%= current_user.kaisuu %>回</div>
    <% end %>
  <% end %>

  <div class="henshu">
    <% if current_user.id == @user.id %>
      <%= link_to "編集する", edit_user_registration_path %>
    <% end %>
  </div>
  
  <div class="kensaku">投稿を検索</div>
  <%= form_tag({controller:"users",action:"show"}, method: :get, class: "search-form") do %>
    <div class="search1"><%= text_field_tag :search %></div>
    <div class="search2"><%= submit_tag '検索する' %></div>
  <% end %>

  <div class="kensaku">自分の投稿一覧</div>
  <% @tweets.each do |t| %>
    <% if @user.id == t.user.id %>
      <div class="tweet">
        <div class="tweet-image">
          <%= image_tag t.image_url, size: "100x100" if t.image? %>
        </div>
        <div class="tweet-content">
          <div class="tweet-name"><%= t.name %></div>
          <div class="tweet-place">場所：<%= t.place %></div>
          <div class="tweet-date">日付：<%= t.memory %></div>
          <div class="tweet-rating">
            星評価：
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span> 
          </div>
          <div class="tweet-links">
            <%= link_to "詳細へ", tweet_path(t.id) %>
            <%= link_to "編集する", edit_tweet_path(t.id) %>
            <%= link_to "削除する", tweet_path(t.id), data: { turbo_method: :delete } %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="back-button">
    <%= link_to "ホームに戻る", tweets_path %>
  </div>
</div>